BEGIN(module)
	MEMBER(module, defs, node_list_t, MT_NODE_LIST)
	MEMBER(module, ns,   node_ns_t,   MT_NS)
END(module)

BEGIN(func)
	MEMBER(func, name, str_t,       MT_STR)
	MEMBER(func, in,   node_list_t, MT_NODE_LIST)
	MEMBER(func, out,  node_list_t, MT_NODE_LIST)
	MEMBER(func, body, node_list_t, MT_NODE_LIST)
	
	MEMBER(func, ns,   node_ns_t,   MT_NS)
	
	MEMBER(func, compiled,          bool,                     MT_BOOL)
	MEMBER(func, linked,            bool,                     MT_BOOL)
	MEMBER(func, as_offset,         size_t,                   MT_SIZE)
	MEMBER(func, stack_frame_size,  size_t,                   MT_SIZE)
	MEMBER(func, addr_slots,        list_t(node_addr_slot_t), MT_ASL )
	MEMBER(func, return_jump_slots, list_t(asm_slot_t),       MT_NONE)
END(func)